/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAudio: typeof import('./components/AppAudio.vue')['default']
    AppChatInput: typeof import('./components/AppChatInput.vue')['default']
    AppDnD: typeof import('./components/AppDnD.vue')['default']
    AppEditor: typeof import('./components/AppEditor.vue')['default']
    AppImages: typeof import('./components/AppImages.vue')['default']
    AppInput: typeof import('./components/AppInput.vue')['default']
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppSearch: typeof import('./components/AppSearch.vue')['default']
    AppSpeech: typeof import('./components/AppSpeech.vue')['default']
    AppTextBlock: typeof import('./components/AppTextBlock.vue')['default']
    AppToolInput: typeof import('./components/AppToolInput.vue')['default']
    AppTools: typeof import('./components/AppTools.vue')['default']
    AppUser: typeof import('./components/AppUser.vue')['default']
    AppView: typeof import('./components/AppView.vue')['default']
    Artifacts: typeof import('./components/Artifacts.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    PageLanding: typeof import('./components/PageLanding.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
  }
}
