/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAudio: typeof import('./components/AppAudio.vue')['default']
    AppTextBlock: typeof import('./components/AppTextBlock.vue')['default']
    AppView: typeof import('./components/AppView.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    LandBanner: typeof import('./components/web/LandBanner.vue')['default']
    LandFeature: typeof import('./components/web/LandFeature.vue')['default']
    LandFooter: typeof import('./components/web/LandFooter.vue')['default']
    LandHero: typeof import('./components/web/LandHero.vue')['default']
    LandIntegrations: typeof import('./components/web/LandIntegrations.vue')['default']
    LandLanding: typeof import('./components/web/LandLanding.vue')['default']
    LandPortfolio: typeof import('./components/web/LandPortfolio.vue')['default']
    LandPromoBanner: typeof import('./components/web/LandPromoBanner.vue')['default']
    LandQuote: typeof import('./components/web/LandQuote.vue')['default']
    LandSponsor: typeof import('./components/web/LandSponsor.vue')['default']
    LandStandar: typeof import('./components/web/LandStandar.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
  }
}
